// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaFlswRdgXy3W2uwSFlhwCSQTexDbvyXM',
    appId: '1:38890409708:web:52ae3060bf3fbfde025fc9',
    messagingSenderId: '38890409708',
    projectId: 'health-tracker-kiet',
    authDomain: 'health-tracker-kiet.firebaseapp.com',
    storageBucket: 'health-tracker-kiet.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWDA_A_vbSUtQmTwqJvcA6mrsAq9FeK70',
    appId: '1:38890409708:android:71967fe651311119025fc9',
    messagingSenderId: '38890409708',
    projectId: 'health-tracker-kiet',
    storageBucket: 'health-tracker-kiet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbam-TASxyx3Sv6f1F7Sau2njjU5Mou0o',
    appId: '1:38890409708:ios:c2ae29476ae7d7e3025fc9',
    messagingSenderId: '38890409708',
    projectId: 'health-tracker-kiet',
    storageBucket: 'health-tracker-kiet.firebasestorage.app',
    iosBundleId: 'com.example.healthTrackerAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbam-TASxyx3Sv6f1F7Sau2njjU5Mou0o',
    appId: '1:38890409708:ios:c2ae29476ae7d7e3025fc9',
    messagingSenderId: '38890409708',
    projectId: 'health-tracker-kiet',
    storageBucket: 'health-tracker-kiet.firebasestorage.app',
    iosBundleId: 'com.example.healthTrackerAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaFlswRdgXy3W2uwSFlhwCSQTexDbvyXM',
    appId: '1:38890409708:web:7660c09c2497f368025fc9',
    messagingSenderId: '38890409708',
    projectId: 'health-tracker-kiet',
    authDomain: 'health-tracker-kiet.firebaseapp.com',
    storageBucket: 'health-tracker-kiet.firebasestorage.app',
  );

}